---
title: "Draft Quarto document"
author:
  - name: Isabell
    affiliations:
      - name: SDU
        address: Street 10
format: html
editor: 
  markdown:
      wrap: 72
      canonical: true
execute:
  echo: true
---

## Header 1

```{r setup}
#| warning: false
#| message: false
targets::tar_config_set(store = here::here("_targets"))
library(tidyverse)
library(targets)
library(tidymodels)
source(here::here("R/functions.R"))
lipidomics <- targets::tar_read(lipidomics)
```

## Results

```{r}
tar_read(df_stats_by_metabolite)
```

```{r}
tar_read(fig_metabolite_distrubution)
```

### Running multiple models

```{r}
targets::tar_read(df_stats_by_metabolite) %>%
  dplyr::mutate(MeanSD = glue::glue("{value_mean} ({value_sd})")) %>%
  dplyr::select(Metabolite = metabolite, `Mean SD` = MeanSD) %>%
  knitr::kable(caption = "Descriptive statistics of the metabolites")
```

```{r}
model_estimates <- lipidomics %>%
  split_by_metabolite() %>%
  purrr::map(generate_model_results) %>%
  purrr::list_rbind() %>%
  dplyr::filter(stringr::str_detect(term, "metabolite_"))

model_estimates
```

```{r}
lipidomics %>%
  dplyr::select(metabolite) %>%
  dplyr::mutate(term = metabolite) %>%
  column_values_to_snake_case(term) %>%
  dplyr::mutate(term = stringr::str_c("metabolite_", term)) %>%
  dplyr::distinct(term, metabolite) %>%
  dplyr::right_join(model_estimates, by = "term")
```

### Figure of model estimates

```{r}
model_estimates <- tar_read(df_model_estimates)
```

```{r}
tar_read(fig_model_estimates)
```
